---
fontsize: 12pt
geometry: margin=1in
linkcolor: black
urlcolor: black
output: pdf_document
header-includes:
- \usepackage{setspace}
- \onehalfspacing
---

```{r setupA, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, highlight=FALSE, message=FALSE)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE, include = FALSE}
library(knitr)
library(tidyverse)

mydata <- read_csv("~/RStudio/STAT 4220 - Biz Analytics/Data/conversion.csv")
mydata$fb_campaign_id <- NULL
mydata$interest <- NULL
names(mydata) <- tolower(names(mydata))
names(mydata)[names(mydata) == "gender"] <- "male"
names(mydata)[names(mydata) == "xyz_campaign_id"] <- "campaign"
names(mydata)[names(mydata) == "total_conversion"] <- "total_conv"
names(mydata)[names(mydata) == "approved_conversion"] <- "app_conv"
mydata$male[mydata$male == 'M'] <- 1
mydata$male[mydata$male == 'F'] <- 0
mydata$male <- as.integer(mydata$male)
mydata$age[mydata$age == '30-34'] <- 32
mydata$age[mydata$age == '35-39'] <- 37
mydata$age[mydata$age == '40-44'] <- 42
mydata$age[mydata$age == '45-49'] <- 47
mydata$age <- as.integer(mydata$age)
mydata$campaign[mydata$campaign == 916] <- "campaign_1"
mydata$campaign[mydata$campaign == 936] <- "campaign_2"
mydata$campaign[mydata$campaign == 1178] <- "campaign_3"
mydata$campaign <- as.factor(mydata$campaign)
```

# Appendix A: Data {-}
```{r, echo=FALSE}
mydata %>%
  select(ad_id : app_conv) %>%
  head(n=335) %>%
  kable(col.names = c("Ad ID", "Campaign", "Age", "Gender", "Impressions", 
          "Clicks", "Spent", "Total Conversion", "Approved Conversion"))
```